spring:
  application:
    name: 12-factor
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=12factorapp;encrypt=false
    username: db_user
    password: <your password here>
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  data:
    mongodb:
      uri: mongodb://db_user:<your password here>@localhost:27017/12factor
      database: 12factor
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 8080
